### ISSUE TITLE
Un-documented requirements

### ISSUE THREAD

**Issue by granthussey** [gerberlab/MDSINE2#11] opened 2022-03-02 14:10 UTC
I was able to get MDSINE2 working on my data, however, I discovered two undocumented requirements/behaviors, and wanted to bring them up:

1. The _time_ column of metadata.
2. You **must** have multiple measurement columns for the qPCR data frame (e.g., the model only ran when qPCR data frame had columns `measurement1`, `measurement2`, AND `measurement3`)

**Comment by yk23** [comment] 2022-08-19 18:39
As I mentioned in the other Issue (#12 ): I'm sorry that we haven't been observing this repository as much -- we are making some additions/cleanups still to the codebase as we are preparing for an additional publication. It's gone through a change of ownership and that was largely the cause for delay.

I think there are a few areas in which the inputs could be better documented. I don't think we formally included the specification for the metadata file.

The qPCR was originally written for triplicates -- but it was intended to work for an arbitrary # of measurements. The fact that it only works with 3 appears to be a bug/oversight. I'll try to addrees this asap.

**Comment by linlin0026** [comment] 2023-06-18 16:42
> As I mentioned in the other Issue (#12 ): I'm sorry that we haven't been observing this repository as much -- we are making some additions/cleanups still to the codebase as we are preparing for an additional publication. The repository/software has gone through a change of management and that was largely the cause for delay.
> 
> 1. I think there are quite a few areas in which the inputs could be better documented. I don't think we formally included the specification for the metadata file. That being said, the _time_ column being required hopefully should not be a surprise --- our underlying model requires the ability to compute the change in timepoints Δt.
> 2. The qPCR input was originally written for triplicates -- but I can't imagine that it wasn't also written to work for an arbitrary # of measurements. The fact that it only works with 3 appears to be a bug/oversight. I'll try to addrees this asap.

Hello, dear Professor. I noticed that mdsine2 has online new preprint, and in the _tutorial_data\replicates-toy\qpcr.tsv_ file you provided for jupyterlab, qpcr still requires three replicate measurements. So I would like to ask how to run **mcmc_negbin = md2.negbin.build_graph** if only one qpcr experiment was performed for each sample ? 
    Thank you very much for reading and replying :)

**Comment by yk23** [comment] 2023-06-20 14:19
Hi @linlin0026, I believe this issue has been fixed over the last few months as we've been pushing out changes for the new preprint. I just pushed out an additional fix for when there is only a single replicate (in which we calculate "0" for the empirical variance)

The tutorial still contains a triplicate experiment for the qPCR replicates, but the latest branch should handle any multiplicity. Let me test it out and get back to you (but feel free to do your own testing in the meantime)

**Comment by linlin0026** [comment] 2023-06-21 07:41
Thanks for your reminder, professor. I have rechecked the original qPCR experimental records and confirmed that duplicates or triplicates were carried out in the experiments. I will use the modified mdsine2/posterior.py to try the model simulation with example files again. Thanks your reply :）

**Comment by yk23** [comment] 2023-06-21 18:37
Great. To our knowledge, this issue has now been addressed so I will be closing it. Feel free to comment if you need it re-opened.

**Closed by yk23** 2023-06-21 18:37 UTC
